name: Validate MCP Configuration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Validate JSON
      run: |
        # Validate documents.json
        jq '.' data/documents.json > /dev/null
        echo "✅ documents.json is valid"
        
        # Validate configurations
        for file in config/*.json; do
          jq '.' "$file" > /dev/null
          echo "✅ $file is valid"
        done
        
    - name: Test Server
      run: |
        # Test if server can load
        timeout 5 node server.js < /dev/null || true
        echo "✅ Server loads successfully"
